# Generated by Django 2.0.6 on 2018-06-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_de_capa', models.ImageField(blank=True, null=True, upload_to='capa')),
                ('nome', models.CharField(max_length=35)),
                ('discricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('discricao', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('dataInicio', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='Data de Termino')),
                ('horaFim', models.TimeField(blank=True, null=True, verbose_name='Hora de Termino')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='compromissoFoto')),
            ],
            options={
                'verbose_name_plural': 'Compromissos',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometarefa', models.CharField(max_length=20, verbose_name='tarefa')),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=45)),
                ('bio', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('foto_de_Perfil', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Agenda.Agenda')),
            ],
            options={
                'verbose_name_plural': 'Agenda Institucional',
            },
            bases=('Agenda.agenda',),
        ),
        migrations.CreateModel(
            name='AgendaPrivada',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Agenda.Agenda')),
            ],
            options={
                'verbose_name_plural': 'Agenda Privada',
            },
            bases=('Agenda.agenda',),
        ),
        migrations.CreateModel(
            name='AgendaPublica',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Agenda.Agenda')),
            ],
            options={
                'verbose_name_plural': 'Agenda Publica',
            },
            bases=('Agenda.agenda',),
        ),
        migrations.CreateModel(
            name='CompromissoInstitucional',
            fields=[
                ('compromisso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Agenda.Compromisso')),
                ('compromisso', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Agenda.Tarefas')),
            ],
            options={
                'verbose_name_plural': 'Compromisso Institucional',
            },
            bases=('Agenda.compromisso',),
        ),
        migrations.CreateModel(
            name='CompromissoPessoal',
            fields=[
                ('compromisso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Agenda.Compromisso')),
                ('compromisso', models.CharField(choices=[('aniversario', 'Aniversário'), ('evento', 'Evento'), ('lembrete', 'Lembrete'), ('meta', 'Meta'), ('outro', 'Outro')], help_text='Tipos de eventos que podem vir a ser criado nesta versão da agenda', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Compromissos Pessoais',
            },
            bases=('Agenda.compromisso',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='Agenda.Usuario'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='Agenda.Usuario'),
        ),
        migrations.AddField(
            model_name='agendapublica',
            name='compromissoPessoal',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoPessoal', verbose_name='Compromissos'),
        ),
        migrations.AddField(
            model_name='agendapublica',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendapublica',
            name='seguem',
            field=models.ManyToManyField(blank=True, related_name='seguem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaprivada',
            name='compromissoPessoal',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoPessoal', verbose_name='Compromissos'),
        ),
        migrations.AddField(
            model_name='agendaprivada',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='compromissoInstitucional',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoInstitucional', verbose_name='Compromisso Institucional'),
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='agendainstitucional',
            name='seguem',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
