# Generated by Django 2.0.5 on 2018-05-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendainstitucional',
            options={'verbose_name_plural': 'Agenda Institucional'},
        ),
        migrations.AlterModelOptions(
            name='agendaprivada',
            options={'verbose_name_plural': 'Agenda Privada'},
        ),
        migrations.AlterModelOptions(
            name='agendapublica',
            options={'verbose_name_plural': 'Agenda Publica'},
        ),
        migrations.AlterModelOptions(
            name='compromisso',
            options={'verbose_name_plural': 'Compromissos'},
        ),
        migrations.AlterModelOptions(
            name='compromissoinstitucional',
            options={'verbose_name_plural': 'Compromisso Institucional'},
        ),
        migrations.AlterModelOptions(
            name='compromissopessoal',
            options={'verbose_name_plural': 'Compromissos Pessoais'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterField(
            model_name='agendapublica',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Usuario'),
        ),
    ]
