# Generated by Django 2.0.5 on 2018-05-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_auto_20180512_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendainstitucional',
            name='compromissoInstitucional',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoInstitucional', verbose_name='Compromisso Institucional'),
        ),
        migrations.AlterField(
            model_name='agendainstitucional',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agenda.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='agendaprivada',
            name='compromissoPessoal',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoPessoal', verbose_name='Compromisso'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='dataFim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do terminio'),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='dataInicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='nometarefa',
            field=models.CharField(max_length=20, verbose_name='tarefa'),
        ),
    ]
