# Generated by Django 2.0.5 on 2018-05-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_auto_20180512_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='discricao',
            field=models.TextField(blank=True),
        ),
    ]
