# Generated by Django 2.0.5 on 2018-05-12 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_auto_20180512_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='discricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
