# Generated by Django 2.0.5 on 2018-05-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_auto_20180512_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromisso',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='agendaprivada',
            name='compromissoPessoal',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoPessoal', verbose_name='Compromissos'),
        ),
        migrations.AlterField(
            model_name='agendapublica',
            name='compromissoPessoal',
            field=models.ManyToManyField(blank=True, to='Agenda.CompromissoPessoal', verbose_name='Compromissos'),
        ),
    ]
