# Generated by Django 2.0.5 on 2018-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_auto_20180512_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromissopessoal',
            name='compromisso',
            field=models.CharField(choices=[('aniversario', 'Aniversário'), ('evento', 'Evento'), ('lembrete', 'Lembrete'), ('meta', 'Meta'), ('outro', 'Outro')], help_text='Tipos de eventos que podem vir a ser criado nesta versão da agenda', max_length=20),
        ),
    ]
