# Generated by Django 2.0.5 on 2018-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0007_auto_20180514_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
