# Generated by Django 2.0.5 on 2018-05-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0008_compromisso_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='hora',
        ),
    ]
